
export const monitoringChecklistItems = [
  "Organizational Structure (Updated / Signed)",
  "Document Control Center",
  "Entrace / Exit Signages",
  "7S (Inside & Out)",
  "EOMS Submissions",
  "Operational Plan",
  "Objectives Monitoring",
  "Risk and Opportunity Registry",
  "Risk and Opportunity Action Plan",
  "Attachments / Evidences",
  "ARTA Signages",
  "Mission/ Vision / Core Values / Quality Policy",
  "Warning Signs and Labels",
  "DPO Seal",
  "Certificate of Occupancy",
  "Emergency Evaluation Postings",
  "Communication Logbooks",
  "Incoming Logbook",
  "Outgoing Logbook",
  "Visitor Logbook",
  "Procedure Manual",
  "Forms Utilized by Units",
  "CSM Form",
  "CSM DropBox / Online Platform",
  "Citizen Charter",
  "CSC ID's of Employees",
  "Fire Extinguisher (With Labels)",
  "Clean Tables of Employees",
  "Fire Exit Stairs Free from Obstructions",
  "Files Documents Based on Pocess",
  "Medicine Cabinet"
];
