
'use client';

import React from 'react';
import type { AccreditationRecommendation } from '@/lib/types';
import { format } from 'date-fns';

interface AccreditationRecommendationReportProps {
  items: {
    programName: string;
    abbreviation: string;
    level: string;
    surveyDate?: string;
    recommendation: AccreditationRecommendation;
  }[];
  unitMap: Map<string, string>;
  scope: 'institutional' | 'program' | 'unit';
  year: number;
  unitName?: string;
}

export function AccreditationRecommendationReport({ items, unitMap, scope, year, unitName }: AccreditationRecommendationReportProps) {
  const currentTitle = scope === 'institutional' 
    ? 'Institutional Accreditation Gaps Registry' 
    : scope === 'unit' 
    ? 'Unit Quality Compliance Audit' 
    : 'Program Accreditation Recommendations';

  return (
    <div className="p-8 text-black bg-white max-w-[8.5in] mx-auto font-serif leading-tight">
      {/* Header */}
      <div className="text-center mb-8 border-b-2 border-black pb-6">
        <h1 className="text-xl font-bold uppercase tracking-tight">Romblon State University</h1>
        <h2 className="text-md font-semibold uppercase tracking-tight mt-1">Quality Assurance Office</h2>
        <div className="mt-6">
          <h2 className="text-lg font-black uppercase underline">{currentTitle}</h2>
          {scope === 'unit' && unitName && (
              <h3 className="text-2xl font-black uppercase text-blue-700 mt-2 tracking-tight">{unitName}</h3>
          )}
          <p className="text-xs font-bold mt-1">ACADEMIC YEAR: {year}</p>
        </div>
      </div>

      {/* Registry Table */}
      <table className="w-full border-collapse border-2 border-black text-[9px] mb-8">
        <thead>
          <tr className="bg-slate-50 font-black text-center uppercase border-b-2 border-black">
            <th className="border border-black p-2 w-[18%]">Program Offering</th>
            <th className="border border-black p-2 w-[8%]">Type</th>
            <th className="border border-black p-2 w-[28%]">Accreditor's Recommendation</th>
            <th className="border border-black p-2 w-[14%]">Action Units</th>
            <th className="border border-black p-2 w-[10%]">Status</th>
            <th className="border border-black p-2 w-[22%]">Action Taken / Updates</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item, i) => (
            <tr key={i} className="border-b border-black">
              <td className="border border-black p-2 align-top">
                <p className="font-black leading-tight">{item.programName}</p>
                <p className="text-[7px] font-bold text-slate-500 mt-1 uppercase">
                    Level: {item.level} | Survey: {item.surveyDate || 'TBA'}
                </p>
              </td>
              <td className="border border-black p-2 text-center align-top font-bold uppercase text-[8px]">
                {item.recommendation.type}
              </td>
              <td className="border border-black p-2 align-top italic leading-relaxed">
                {item.recommendation.text}
                {item.recommendation.additionalInfo && (
                    <div className="mt-2 pt-2 border-t border-slate-100 not-italic text-[7px] font-bold">
                        <span className="uppercase text-slate-400 mr-1">Admin Notes:</span>
                        {item.recommendation.additionalInfo}
                    </div>
                )}
              </td>
              <td className="border border-black p-2 align-top">
                <ul className="list-disc pl-4 space-y-1">
                    {(item.recommendation.assignedUnitIds || []).map(uid => (
                        <li key={uid} className="font-bold leading-tight">{unitMap.get(uid) || uid}</li>
                    ))}
                </ul>
              </td>
              <td className="border border-black p-2 text-center align-top font-black uppercase text-[8px]">
                {item.recommendation.status}
              </td>
              <td className="border border-black p-2 align-top min-h-[60px]">
                  {/* Blank space for manual updates */}
              </td>
            </tr>
          ))}
          {items.length === 0 && (
            <tr><td colSpan={6} className="p-8 text-center italic text-gray-400">No pending recommendations recorded for this cycle.</td></tr>
          )}
        </tbody>
      </table>

      {/* Footer Meta */}
      <div className="mt-20 grid grid-cols-2 gap-20">
        <div className="text-center">
          <p className="text-[10px] uppercase font-bold text-left mb-8 opacity-60">Generated by:</p>
          <div className="border-b border-black font-bold text-sm pb-1 mb-1">
            RSU EOMS PORTAL
          </div>
          <p className="text-[10px] uppercase font-semibold">Institutional Digital Registry</p>
        </div>
        <div className="text-center">
          <p className="text-[10px] uppercase font-bold text-left mb-8 opacity-60">Verified by:</p>
          <div className="border-b border-black font-bold text-sm pb-1 mb-1 min-h-[1rem]">
          </div>
          <p className="text-[10px] uppercase font-semibold">Director, Quality Assurance Office</p>
        </div>
      </div>

      <div className="mt-16 text-[9px] text-gray-400 italic text-center border-t pt-4">
        This is an official system-generated document issued via RSU EOMS Portal. 
        Authenticated Accountability Registry AY {year}.
      </div>
    </div>
  );
}
